name: docker-nginx

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  deploy:
    uses: unb-libraries/dockworker/.github/workflows/build-push-notify.yaml@6.x
    with:
      image-name: 'ghcr.io/unb-libraries/nginx'
      push-branches: '["3.x"]'
    secrets:
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
